/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.ListaAlbum;
import Control.CadastrarArtista;
import Control.CadastrarMusica;
import Control.ListaPlaylist;
import Control.Playlist;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno
 */
public class adicionar extends javax.swing.JFrame {

    /**
     * Creates new form adicionar
     */
    
    CadastrarMusica cm;
    CadastrarArtista ca;
    ListaAlbum cal;
    ListaPlaylist lpl;
    index formi;
            
    public adicionar(index i, CadastrarMusica a, CadastrarArtista b, ListaAlbum c, ListaPlaylist d) {
        initComponents(); 
        formi = i;
        cm = a;
        ca = b;
        cal = c;
        lpl = d;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel1Op = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnProximo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbArtista = new javax.swing.JRadioButton();
        rbMusica = new javax.swing.JRadioButton();
        rbAlbum = new javax.swing.JRadioButton();
        rbPlaylist = new javax.swing.JRadioButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1Op.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("O que gostaria de adicionar?");

        btnProximo.setText("Próximo");
        btnProximo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProximoMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        rbArtista.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rbArtista);
        rbArtista.setForeground(new java.awt.Color(255, 255, 255));
        rbArtista.setText("Artista");
        rbArtista.setActionCommand("artista");

        rbMusica.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rbMusica);
        rbMusica.setForeground(new java.awt.Color(255, 255, 255));
        rbMusica.setText("Música");
        rbMusica.setActionCommand("musica");

        rbAlbum.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rbAlbum);
        rbAlbum.setForeground(new java.awt.Color(255, 255, 255));
        rbAlbum.setText("Álbum");
        rbAlbum.setActionCommand("album");

        rbPlaylist.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rbPlaylist);
        rbPlaylist.setForeground(new java.awt.Color(255, 255, 255));
        rbPlaylist.setText("Playlist");
        rbPlaylist.setActionCommand("playlist");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbAlbum)
                    .addComponent(rbMusica)
                    .addComponent(rbArtista)
                    .addComponent(rbPlaylist))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(rbArtista)
                .addGap(18, 18, 18)
                .addComponent(rbMusica)
                .addGap(18, 18, 18)
                .addComponent(rbAlbum)
                .addGap(18, 18, 18)
                .addComponent(rbPlaylist)
                .addContainerGap())
        );

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panel1OpLayout = new javax.swing.GroupLayout(panel1Op);
        panel1Op.setLayout(panel1OpLayout);
        panel1OpLayout.setHorizontalGroup(
            panel1OpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1OpLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(panel1OpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1OpLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1OpLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(btnProximo)
                .addGap(93, 93, 93))
        );
        panel1OpLayout.setVerticalGroup(
            panel1OpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1OpLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1OpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProximo)
                    .addComponent(btnCancelar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1Op, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1Op, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProximoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProximoMousePressed
        // TODO add your handling code here:
        
        try
        {
         
            switch (buttonGroup1.getSelection().getActionCommand())
            {
                case "artista":
                    adicionar_artista a = new adicionar_artista(formi, ca);
                    a.setVisible(true);
                    a.setLocationRelativeTo(null);
                    this.dispose();
                break;
                case "musica":
                    if (ca.getSize() == 0)
                    {
                        JOptionPane.showMessageDialog(null, "Não existe Artistas cadastrados. Por favor, cadastre ao menos um Artista");
                    }
                    else
                    {
                        adicionar_musica m = new adicionar_musica(formi, cm, ca);
                        m.setVisible(true);
                        m.setLocationRelativeTo(null);
                        this.dispose();
                    }
                break;
                case "album":
                    if(cm.getSize() == 0)
                    {
                        JOptionPane.showMessageDialog(null, "Não existe Músicas cadastrados. Por favor, cadastre ao menos uma Música");
                    }
                    else
                    {
                        adicionar_album al = new adicionar_album(formi, cal, cm, ca);
                        al.setVisible(true);
                        al.setLocationRelativeTo(null);
                        this.dispose();
                    }

                break;
                case "playlist":
                    if(cm.getSize() == 0)
                    {
                        JOptionPane.showMessageDialog(null, "Não existe Músicas cadastrados. Por favor, cadastre ao menos uma Música");
                    }
                    else
                    {
                        adicionar_playlist p = new adicionar_playlist(formi, lpl, cm);
                        p.setVisible(true);
                        p.setLocationRelativeTo(null);
                        this.dispose();
                    }
                break;
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Marque uma caixa para continuar");
        }
        
        
    }//GEN-LAST:event_btnProximoMousePressed

    private void btnCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMousePressed
        // TODO add your handling code here:
        
        formi.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnCancelarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adicionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new adicionar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnProximo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel1Op;
    private javax.swing.JRadioButton rbAlbum;
    private javax.swing.JRadioButton rbArtista;
    private javax.swing.JRadioButton rbMusica;
    private javax.swing.JRadioButton rbPlaylist;
    // End of variables declaration//GEN-END:variables
}
